name: Generate Snake Game from GitHub Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:     # Memungkinkan eksekusi manual via GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: ezaco-dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: 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
